routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', 'HomeController@getComingSoon')->name('coming-soon');
Route::middleware(['throttle:global'])->group(function () {
    Route::get('/', [Controllers\HomeController::class, 'getHome'])
        ->name('home');
    // Route::get('tweet/{tweet:id}', [Controllers\HomeController::class, 'getTweet'])
    //     ->name('tweet.get');
    // Route::get('user/{id}', [Controllers\HomeController::class, 'getTweetUser'])
    //     ->name('tweet-user.get');
    // Route::get('live', [Controllers\HomeController::class, 'getLive'])
    //     ->name('live');
    // Route::get('search-user', [Controllers\HomeController::class, 'getSearchUser'])
    //     ->name('search.user');
    Route::post('add', [Controllers\HomeController::class, 'add'])
        ->middleware(['throttle:post-limit']);
    Route::get('points', [Controllers\HomeController::class, 'getPoints']);

    Route::middleware(['auth'])->prefix('badmin')->name('badmin.')->group(function () {
        Route::get('/', [Controllers\Badmin\AdminController::class, 'index'])
            ->name('home');
        Route::resource('user', Controllers\Badmin\UserController::class);
        Route::get('points/approved', [Controllers\Badmin\PointController::class, 'getApprovedList'])
            ->name('points-approved');
        Route::get('points/rejected', [Controllers\Badmin\PointController::class, 'getRejectedList'])
            ->name('points-rejected');
        Route::resource('points', Controllers\Badmin\PointController::class);
    });

    Auth::routes(['register' => false]);
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Badmin/AdminController.php
<?php

namespace App\Http\Controllers\Badmin;

use Illuminate\Http\Request;

use App\Http\Controllers\Controller;

class AdminController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        // $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        $matomoIframeURL = null;

        if (config('services.matomo.api_key')) {
            $matomoIframeURL = config('services.matomo.host');
            $matomoIframeURL .= 'index.php?module=Widgetize&action=iframe&moduleToWidgetize=Dashboard&actionToWidgetize=index&idSite=';
            $matomoIframeURL .= config('services.matomo.site_id');
            $matomoIframeURL .= '&period=week&date=yesterday&token_auth=';
            $matomoIframeURL .= config('services.matomo.api_key');
        }

        return view('badmin.home', [
            'matomoIframeURL' => $matomoIframeURL,
        ]);
    }
}

app/Http/Controllers/Badmin/PointController.php
<?php

namespace App\Http\Controllers\Badmin;

use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Validation\Rule;
use Illuminate\View\View;

use App\Http\Controllers\Controller;
use App\Models\Point;

class PointController extends Controller
{
    public function index()
    {
        $list = Point::whereNull('approved_at')
            ->whereNull('rejected_at')
            ->orderBy('created_at', 'asc')
            ->orderBy('id', 'asc')
            ->paginate(100);

        return view('badmin.point.index', [
                'list' => $list,
            ]);
    }

    public function getApprovedList()
    {
        $list = Point::whereNotNull('approved_at')
            ->with('actionTakenBy')
            ->orderBy('approved_at', 'desc')
            ->orderBy('id', 'asc')
            ->paginate(100);

        return view('badmin.point.index-approved', [
                'list' => $list,
            ]);
    }

    public function getRejectedList()
    {
        $list = Point::whereNotNull('rejected_at')
            ->with('actionTakenBy')
            ->orderBy('rejected_at', 'desc')
            ->orderBy('id', 'asc')
            ->paginate(100);

        return view('badmin.point.index-rejected', [
                'list' => $list,
            ]);
    }

    public function update(int $pointId)
    {
        $point = Point::findOrFail($pointId);
        $point->rejected_at = null;
        $point->approved_at = now();
        $point->action_taken_by_id = auth()->id();
        $point->save();

        return redirect()->back()
            ->with([
                'success' => 'Approved',
            ]);
    }

    public function destroy(int $pointId)
    {
        $point = Point::findOrFail($pointId);
        $point->approved_at = null;
        $point->rejected_at = now();
        $point->action_taken_by_id = auth()->id();
        $point->save();

        return redirect()->back()
            ->with([
                'success' => 'Rejected',
            ]);
    }
}

app/Http/Controllers/Badmin/UserController.php
<?php

namespace App\Http\Controllers\Badmin;

use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Validation\Rule;
use Illuminate\View\View;

use App\Http\Controllers\Controller;
use App\Models\User;
use App\Services\UserService;

class UserController extends Controller
{
    /**
     * @var UserService
     */
    protected $userService;

    public function __construct(
        UserService $userService
    ) {
        $this->userService = $userService;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(): View
    {
        $list = $this->userService->getAdminList();

        return view('badmin.user.index', [
            'list' => $list,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(): View
    {
        return view('badmin.user.form', [
            'user' => new User(),
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request): RedirectResponse
    {
        $postData = $request->validate([
            'name' => 'required|min:2',
            'email' => 'required|email|unique:users,email',
            'password' => 'nullable|min:8',
        ]);

        // if (!\array_key_exists('active', $postData)) {
        //     $postData['active'] = false;
        // }

        $user = $this->userService->save(new User(), $postData);

        return redirect()->to(route('badmin.user.edit', $user->id))
            ->with('success', __('Kaydedildi'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\User $user
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request, User $user): View
    {
        return view('badmin.user.form', [
            'user' => $user,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\User $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user): RedirectResponse
    {
        $postData = $request->validate([
            'name' => 'required|min:2',
            'email' => 'required|email|unique:users,email,' . $user->id,
            'password' => 'nullable|min:8',
        ]);

        $user = $this->userService->save($user, $postData);

        return redirect()->back()
            ->with('success', __('Kaydedildi'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\User $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user): RedirectResponse
    {
        $user->delete();

        return redirect()->back()
            ->with('success', __('Silindi'));
    }
}

resources/views/badmin/user/form.blade.php
@extends('layouts.admin')

@section('header')
  <h3>{{ $user->id ? $user->title : __('Add New User') }}</h3>
@endsection

@section('content')
  <form
    class="user-form"
    action="{{ $user->id ? route('badmin.user.update', $user->id) : route('badmin.user.store') }}"
    method="post"
    enctype="multipart/form-data"
  >
    @if ($user->id)
      <input type="hidden" name="_method" value="put">
    @endif

    @csrf

    <div class="form-group">
      <label for="name">{{ __('Name') }}</label>
      <input
        type="text"
        name="name"
        class="form-control"
        id="name"
        maxlength="255"
        minlength="5"
        required
        value="{{ old('name') ?: $user->name }}"
        aria-describedby="name-desc"
      >
      <small class="form-text text-muted" id="name-desc">
        Full name of user.
      </small>
    </div>

    <div class="form-group">
      <label for="email">{{ __('E-mail') }}</label>
      <input
        type="email"
        name="email"
        class="form-control"
        id="email"
        maxlength="255"
        minlength="5"
        required
        value="{{ old('email') ?: $user->email }}"
      >
    </div>

    <div class="form-group">
      <label for="password">{{ __('Password') }}</label>
      <input
        type="password"
        name="password"
        class="form-control"
        id="password"
        maxlength="255"
        minlength="8"
        value="{{ old('password') }}"
        aria-describedby="passwordDesc"
      >
      @if($user->id)
        <small class="form-text text-muted" id="passwordDesc">
          Enter the new password to change password.
        </small>
      @endif
    </div>

    <div class="text-right">
      <button type="submit" class="btn btn-outline-primary">{{ __('Save') }}</button>
    </div>

  </form>

@endsection

resources/views/badmin/user/index.blade.php
@extends('layouts.admin')

@section('header')
  <div class="row">
    <div class="col-12 col-md-8">
      <h3>{{ __('Users') }}</h3>
    </div>
    <div class="col-12 col-md-4 text-xs-center text-md-right">
      <a class="btn btn-outline-dark btn-sm" href="{{ route('badmin.user.create') }}">
        {{ __('Add New User') }}
      </a>
    </div>
  </div>
@endsection

@section('content')
  <table class="table table-striped">
    <thead>
      <tr>
        <th>{{ __('Name') }}</th>
        <th>{{ __('E-mail') }}</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      @foreach($list as $item)
        <tr>
          <td>{{ $item->name }}</td>
          <td>{{ $item->email }}</td>
          <td class="text-right">
              <a
                class="btn btn-outline-info btn-sm"
                href="{{ route('badmin.user.edit', [$item->id,]) }}"
              >{{ __('Edit') }}</a>
            <form class="d-inline" action="{{ route('badmin.user.destroy', $item->id) }}" method="post">
              @csrf
              <input type="hidden" name="_method" value="delete">
              <button type="submit" class="btn btn-outline-danger btn-sm" data-ask="{{ __('Are you sure want to delete this user?') }}">
                {{ __('Remove') }}
              </button>
            </form>
          </td>
        </tr>
      @endforeach
    </tbody>
  </table>

  {!! $list->render() !!}

  @if($list->count() === 0)
    <p class="text-center">
      {{ __('No users.') }}
    </p>
  @endif
@endsection